Tinytable
eddelbuettel/gsir-te pull request #6
Opened 2024-11-26 02:21 UTC by grantmcdermott

Mini PR that swaps kableExtra (40+ recursive deps) for tinytable (0 deps).

P.S. No changes to the PDF b/c I can't knit your .Rmd file. I don't think it's my PR b/c the same is true for the untouched master branch. But... copying the text across to a fresh pinp template works without a hitch. So there's something off in the current YAML. Same error across multiple machines and IDEs.

```
/usr/lib/rstudio/resources/app/bin/quarto/bin/tools/x86_64/pandoc +RTS -K512m -RTS Getting-Started-in-R.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output Getting-Started-in-R.tex --lua-filter /usr/lib/R/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /usr/lib/R/library/rmarkdown/rmarkdown/lua/latex-div.lua --embed-resources --standalone --template /usr/lib/R/library/pinp/rmarkdown/templates/pdf/resources/template.tex --highlight-style tango --pdf-engine pdflatex --natbib --include-in-header /tmp/RtmpQvKRcu/rmarkdown-str327113144b78.html 
output file: Getting-Started-in-R.knit.md

! LaTeX Error: Missing \begin{document}.

Error: LaTeX failed to compile Getting-Started-in-R.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See Getting-Started-in-R.log for more info.
Execution halted
```

2024-11-26 02:49 UTC, eddelbuettel commented
> `! LaTeX Error: Missing \begin{document}.`

I get that too (before your PR).  So something changed :man_shrugging:

2024-11-26 02:54 UTC, eddelbuettel commented
It works if you use a current `pinp.cls` rather than the one in the repo.  Maybe copy it in by hand now, I'll update the repo and you can then rebase to it.

2024-11-26 02:55 UTC, eddelbuettel commented
But the real PR we want here, of course, is `tinyplot`.  Are you game?

2024-11-26 02:59 UTC, eddelbuettel commented
It also works if you just delete `pinp.cls` as the standard processing step will copy a new (hence current) version in if one is missing, but I suppose it does not overwrite stale ones.

2024-11-26 13:14 UTC, eddelbuettel requested changes
Please rebase and then test locally

2024-11-26 16:57 UTC, eddelbuettel commented
Are you able to build locally after the ~requested rebase~ executed merge?

2024-11-26 17:03 UTC, eddelbuettel reviewed
Ewww.

Can we minimise the spurious whitespace changes to the (goes counting) two lines that matter?  Could you maybe (just for once) use a different editor?

Please do not commit the .log and .pdf files.

2024-11-26 17:04 UTC, grantmcdermott commented
All done, thanks for the hint. Knitted PDF attached.

(Personally, I'm not much of a fan of striped tables but I wanted to maintain consistency with the original kableExtra version. Can remove if you'd like?)

tinyplot PR incoming once we submit the next version to CRAN...

2024-11-26 17:06 UTC, grantmcdermott commented
> Can we minimise the spurious whitespace changes to the (goes counting) two lines that matter? Could you maybe (just for once) use a different editor?

In my defence, I only switched to an different IDE to try a canonical R Markdown builder...

> Please do not commit the .log and .pdf files.

Cool. Will revert. Also: Shouldn't the log file be added to .gitignore?

2024-11-26 17:08 UTC, eddelbuettel commented
>   Shouldn't the log file be added to .gitignore?

Yes, good idea!  

I am wondering if `pinp.cls` should be added too to ensure the build always copies a fresh one in.  OTOH it changes so rarely so we can probably leave it as is.

2024-11-26 17:14 UTC, grantmcdermott commented
> > Shouldn't the log file be added to .gitignore?
> 
> Yes, good idea!
> 
> I am wondering if `pinp.cls` should be added too to ensure the build always copies a fresh one in. OTOH it changes so rarely so we can probably leave it as is.

I would add it too, otherwise you're going to run into the same issue with other PRs... LMK if you agree and I'll make the change.

2024-11-26 17:20 UTC, eddelbuettel commented
> I would add it too, otherwise you're going to run into the same issue with other PRs... LMK if you agree and I'll make the change.

I committed it four hours ago in e0e26277f18e1c94da4fda2f23a3d45add61aa1f which was the reason to ask you for a rebase. The fact that you can now build the pdf is a good proof of this pudding that we do not need `pinp.cls` (for now, or ever) in there.  It really was a one-off change in latex or the pnas setup or I-forget-what.  And we took care of it.

I should probably add a 'buildMe.sh' script that cleans up the copied-in-on-the-fly `pinp.cls` and removes the log file etc.  Would conflict with caching files though so maybe not clean those.  Anyway...

2024-11-26 17:31 UTC, grantmcdermott commented
Done.

FWIW, I had to edit the .R version of the file by hand, because the knitr::purl() conversion is introducing a bunch of formatting changes (mostly related to section divisions) . I'll let you handle that and the final PDF conversion , though.

2024-11-26 18:16 UTC, eddelbuettel approved these changes

2024-11-26 18:16 UTC, eddelbuettel commented on .gitignore
> +**/*.log
Fancy. As there can be only one I usually just write it out but I tip my head...

2024-11-26 18:16 UTC, eddelbuettel commented on Getting-Started-in-R.R
> +  format_tt(escape = TRUE)
Appreciate the minimization.

2024-11-26 20:18 UTC, eddelbuettel commented
The table look I can live with / like better, but any idea why we are now on nine page?  

Old on the, new (your branch) on the right.

![image](https://github.com/user-attachments/assets/9fe876b0-0506-431d-80c0-92f33c057321)

2024-11-26 20:39 UTC, eddelbuettel commented
Classic.  It is three things I can see so far:

1. `apropos(mean)` now returns 17 hits instead of 16, so as a quick fix / hack I add `|> head(16)`
2. `ggplot2`, of course, changed interfaces and `stat.summary(fun.y="...")` now have to be just `stat.summary(fun="...")`
3. Same as 2. in another spot :grinning: 

There is remainder on the last page.  You actually see that on the screenshot above.  One result print 'breaks' the row length.  That probably requires tweaking locally.   If you have a few minutes I would really appreciate a poke.

2024-11-26 20:40 UTC, eddelbuettel commented
Oh, I know: it is `data.table` printing the column type (which I like myself and have as local option here).  Let me see if I can turn that off.

2024-11-26 20:45 UTC, eddelbuettel commented
Yep.  Adding `datatable.print.class=FALSE` to options() did it.  

Do you have preference for me committing this into your branch and PR, versus afterwards?

2024-11-26 21:11 UTC, grantmcdermott commented
> Yep. Adding `datatable.print.class=FALSE` to options() did it.

Yeah. The issue here is that it actually causes the last columns to spill over in its entirety (because of the narrowness of the pinp format). So it ends up being more than just the "marginal" change of a 1 row addition. A pity because, like you, I also like this new print method (and even submitted the original FR on the data.table repo!). But needs must.

> Do you have preference for me committing this into your branch and PR, versus afterwards?
> 
> PS One more. I find the last page breaks better without `options(tinytable_theme_placement_latex_float = "H")`

Go for it. Happy for you to make whatever changes you wish.

2024-11-26 21:16 UTC, grantmcdermott commented
One more thing: the original `kableExtra` chunk was wrapped with `echo = FALSE`, which I deleted for this `tinytable` version. (There's a nice congruency with DT's `i` and `j` logic in TT, which helps to reinforce concepts.) I think it ends up being a wash in the aggregate b/c you don't have to explain the missing code that produces the table, but fwiw...

2024-11-26 21:21 UTC, eddelbuettel commented
Yes, I noticed the reappearances.   

I just bulk-committed this to your repo.

2024-11-27 13:43 UTC, eddelbuettel commented
Ok, couldn't resist so I linearized your git hit history for you as this is a non-'squash-merge'-repo (so far).

2024-11-27 13:44 UTC, merged